### ISSUE TITLE
MEICA pipeline producing output with different Dimensions for two task runs

### ISSUE THREAD

**Issue by sameera2004** [ME-ICA/me-ica#15]
Hi,
We used meica.py to pre process Multi Echo fMRI data collected at Stony Brook university. However, we are getting an error when we are trying to use the produced MEICA outputs in another pipeline.

The issue seems to be that the MEICA pipeline is producing outputs with different dimensions (. Insight_1_medn.nii.gz [41x47x38] , Insight_2_medn.nii.gz [40x47x38]).
These are two task runs from the same subject, and these need to be combined for next step.  However, the program fails at the step of trying to combine them, presumably because of the different dimensions. Prior to running MEICA, all the dimensions are the same across task runs and subjects, so this must be happening due to MEICA.

Do you have any suggestions for fixing this and harmonizing the dimensions? Have you seen this before.

Thank you very much
Sameera

**Comment by dowdlelt** [comment]
Hi Sameera, 

work on meica has been discontinued, as per @emdupre comments in #12 . Folks are now recommended that processing is done with afni_proc or fmriprep. See #12 for locations to get more information. 

That said, it is likely that the issue is due to how meica removes empty slices around the image data, reducing the dimensions. I have seen this if masking during the meica pipeline decides to remove a bit more non brain tissue. Then meica reduces the matrix size, since it is just going to be a bunch of zeros, taking up space. ...

One thing you could check is if the data are still roughly aligned - it may be possible to add a empty slice of zeros (3dzeropad perhaps?) and then continue processing - though some correction for between run movement may be needed. 

Another option is to include an anatomical image in the meica processing stream - that will insure that the data are aligned to a common space (subject, or +orig space in AFNI parlance). 

You could also process the data up until the volreg step with afni_proc and then use the version of tedana you currently have with meica to perform denoising. Or use the new version of tedana that is currently being developed. Basic volreg instructions can be found in this issue https://github.com/ME-ICA/tedana/issues/253

Hope this helps, 
Logan

**Comment by sameera2004** [comment]
Hi Logan,

Thank you very much for the reply. I agree with you MEICA may be removing the empty slices around the image data. We will try you suggestions to process these data.

Since MEICA work has been discontinued we will look into afni_proc or fmriprep to pre process our future Multi echo fMRI data

Thank again
Sameera
